### ISSUE TITLE
tweety.exceptions.TwitterError: [34] Sorry, that page does not exist

### ISSUE THREAD

**Issue by Jaden024** [mahrtayyab/tweety#219] opened 2024-11-20 00:47 UTC
Everyone has this issue now, please update 

tweety.exceptions.TwitterError: [34] Sorry, that page does not exist

**Comment by changchiyou** [comment] 2024-11-20 01:52
https://github.com/changchiyou/wildrift-news-feeds/actions/runs/11924580799/job/33235168624#step:10:1

```shell
2024-11-20 00:55:38,829.829 INFO twitter - generate_twitter_rss: `./twitter.toml` loaded successfully
2024-11-20 00:55:38,921.921 INFO _client - _send_single_request: HTTP Request: POST https://api.x.com/1.1/guest/activate.json "HTTP/2 200 OK"
2024-11-20 00:55:38,992.992 INFO _client - _send_single_request: HTTP Request: GET https://api.x.com/1.1/account/settings.json?include_mention_filter=True&include_nsfw_user_flag=True&include_nsfw_admin_flag=True&include_ranked_timeline=True&include_alt_text_compose=True&ext=ssoConnections&include_country_code=True&include_ext_dm_nsfw_media_filter=True&include_ext_sharing_audiospaces_listening_data_with_followers=True "HTTP/2 404 Not Found"
Traceback (most recent call last):
  File "/home/runner/work/wildrift-news-feeds/wildrift-news-feeds/twitter.py", line 187, in <module>
    generate_twitter_rss()
  File "/home/runner/work/wildrift-news-feeds/wildrift-news-feeds/twitter.py", line 27, in generate_twitter_rss
    twitter.load_cookies(cookie_value)
  File "/opt/hostedtoolcache/Python/3.10.[15](https://github.com/changchiyou/wildrift-news-feeds/actions/runs/11924580799/job/33235168624#step:10:16)/x64/lib/python3.10/site-packages/tweety/auth.py", line 126, in load_cookies
    return self.connect()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/tweety/auth.py", line 22, in connect
    self.request.verify_cookies()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/tweety/http.py", line 226, in verify_cookies
    response = self.__get_response__(**data)
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/tweety/http.py", line [18](https://github.com/changchiyou/wildrift-news-feeds/actions/runs/11924580799/job/33235168624#step:10:19)5, in __get_response__
    return GenericError(
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/tweety/types/n_types.py", line 72, in __init__
    self._raise_exception()
  File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/tweety/types/n_types.py", line 92, in _raise_exception
    raise TwitterError(
tweety.exceptions.TwitterError: [34] Sorry, that page does not exist
Error: Process completed with exit code 1.
```

**Comment by CrossDarkrix** [comment] 2024-11-20 02:43
I temporarily fix that error.
I got it working with this fix.
https://github.com/CrossDarkrix/tweety/commit/9c1c3628a44bd109ef5e2fb1606fb46e557675d6

**Comment by JiroWaze** [comment] 2024-11-20 05:17
> I temporarily fix that error. I got it working with this fix. [CrossDarkrix@9c1c362](https://github.com/CrossDarkrix/tweety/commit/9c1c3628a44bd109ef5e2fb1606fb46e557675d6)

Great work!  mahrtayyab should merge your modification as soon as possible

**Comment by changchiyou** [comment] 2024-11-20 07:14
> I temporarily fix that error. I got it working with this fix. [CrossDarkrix@9c1c362](https://github.com/CrossDarkrix/tweety/commit/9c1c3628a44bd109ef5e2fb1606fb46e557675d6)

Are you going to create a pull request?

**Comment by CrossDarkrix** [comment] 2024-11-20 08:52
I just submitted a pull request.

**Comment by mahrtayyab** [comment] 2024-11-20 10:59
It was a temporary issue on Twitter seems to be fixed now.

**Comment by seleron** [comment] 2024-11-21 19:19
I can confirm this was a temporary issue on Twitter and seems to be fixed on my end as well. Closing other issue.

**Comment by zaksiddiqengineer** [comment] 2024-11-22 00:28
seems the issues is back up?

**Comment by changchiyou** [comment] 2024-11-22 01:20
> seems the issues is back up?

Same here.

**Comment by CrossDarkrix** [comment] 2024-11-22 01:53
Since you pointed out that it is not a good idea to remove all errors,
The error is ignored only when error 34 occurs.
But I had to remove the "verify cookies".
https://github.com/CrossDarkrix/tweety/commit/25d50c41e387e7b9990a860f778c3756f7b8a06b

**Comment by lionel1993** [comment] 2024-11-22 02:09
> seems the issues is back up?

Same here.

**Comment by Cryptojoyz** [comment] 2024-11-22 09:45
Same... What should we do?

**Comment by mahrtayyab** [comment] 2024-11-22 09:50
Twitter started verifying 'x-client-transaction-id' header, working on it , update will be pushed in 6 hours.

**Comment by mahrtayyab** [comment] 2024-11-22 14:55
Issue is fixed , pushing update after more testing

**Comment by alarno** [comment] 2024-11-22 17:19
> Issue is fixed , pushing update after more testing

please push update, we need this 🙏

**Comment by mahrtayyab** [comment] 2024-11-22 20:04
https://github.com/mahrtayyab/tweety/commit/650981ce9605e6e06f2c5c1fe2db5c01a5270d2e

**Closed by mahrtayyab** 2024-11-22 20:04 UTC

**Comment by seleron** [comment] 2024-11-23 00:04
The updated code doesn't work properly for me.

When tried without a session file getting this error: 

2024-11-22 23:54:10 DEBUG:receive_response_headers.started request=<Request [b'GET']> stream_id=3 
2024-11-22 23:54:10 DEBUG:receive_response_headers.failed exception=RuntimeError('<asyncio.locks.Event object at 0xXXXXXXXX [unset]> is bound to a different event loop')
2024-11-22 23:54:10 DEBUG:response_closed.started stream_id=3
2024-11-22 23:54:10 DEBUG:response_closed.complete
2024-11-22 23:54:10 ERROR:Authentication failed: invalid response
2024-11-22 23:54:10 ERROR:Authentication failed: invalid response
Traceback (most recent call last):
  File "<ANONYMIZED_PATH>/<ANONYMIZED_FILE>.py", line 39, in authenticate
    self.perform_authentication(username, password, extra)
  File "<ANONYMIZED_PATH>/<ANONYMIZED_FILE>.py", line 63, in perform_authentication
    raise auth_error
  File "<ANONYMIZED_PATH>/<ANONYMIZED_FILE>.py", line 55, in perform_authentication
    self.twitter_app.start(username, password, extra=extra)
  File "<ANONYMIZED_PATH>/site-packages/tweety/__init__.py", line 21, in wrapper
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/auth.py", line 56, in start
    return await self.sign_in(username, password, extra=_extra)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/auth.py", line 103, in sign_in
    return await self._login()
           ^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/auth.py", line 164, in _login
    response = await self.request.login(self._login_url, _payload=_login_payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/http.py", line 342, in login
    response = await self.__get_response__(True, **request_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/http.py", line 176, in __get_response__
    await self._init_local_api()
  File "<ANONYMIZED_PATH>/site-packages/tweety/http.py", line 167, in _init_local_api
    self._transaction = TransactionGenerator(home_page_html)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/transaction.py", line 105, in __init__
    self.home_page_html = self.validate_response(home_page_html)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/transaction.py", line 129, in validate_response
    raise Exception("invalid response")
Exception: invalid response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ANONYMIZED_PATH>/<ANONYMIZED_FILE>.py", line 107, in main
    trend_fetcher.authenticate(username=username, password=password)
  File "<ANONYMIZED_PATH>/<ANONYMIZED_FILE>.py", line 42, in authenticate
    self.perform_authentication(username, password, extra)
  File "<ANONYMIZED_PATH>/<ANONYMIZED_FILE>.py", line 63, in perform_authentication
    raise auth_error
  File "<ANONYMIZED_PATH>/<ANONYMIZED_FILE>.py", line 55, in perform_authentication
    self.twitter_app.start(username, password, extra=extra)
  File "<ANONYMIZED_PATH>/site-packages/tweety/__init__.py", line 21, in wrapper
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/auth.py", line 56, in start
    return await self.sign_in(username, password, extra=_extra)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/auth.py", line 103, in sign_in
    return await self._login()
           ^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/auth.py", line 164, in _login
    response = await self.request.login(self._login_url, _payload=_login_payload)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/http.py", line 342, in login
    response = await self.__get_response__(True, **request_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/http.py", line 176, in __get_response__
    await self._init_local_api()
  File "<ANONYMIZED_PATH>/site-packages/tweety/http.py", line 167, in _init_local_api
    self._transaction = TransactionGenerator(home_page_html)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/transaction.py", line 105, in __init__
    self.home_page_html = self.validate_response(home_page_html)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/transaction.py", line 129, in validate_response
    raise Exception("invalid response")
Exception: invalid response 

When tried with session file and cookie, getting this error:

2024-11-23 00:02:47 DEBUG:response_closed.started stream_id=17
2024-11-23 00:02:47 DEBUG:response_closed.complete
2024-11-23 00:02:47 ERROR:Authentication failed: 'Request' object has no attribute 'set_cookies'
2024-11-23 00:02:47 ERROR:Authentication failed: 'Request' object has no attribute 'set_cookies'
Traceback (most recent call last):
  File "<ANONYMIZED_PATH>/<ANONYMIZED_FILE>.py", line 34, in authenticate
    self.twitter_app.connect()
  File "<ANONYMIZED_PATH>/site-packages/tweety/__init__.py", line 21, in wrapper
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/auth.py", line 22, in connect
    await self.request.verify_cookies()
  File "<ANONYMIZED_PATH>/site-packages/tweety/http.py", line 317, in verify_cookies
    raise InvalidCredentials(None, None, None)
tweety.exceptions.InvalidCredentials: The Cookies are Invalid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ANONYMIZED_PATH>/<ANONYMIZED_FILE>.py", line 107, in main
    trend_fetcher.authenticate(username=username, password=password)
  File "<ANONYMIZED_PATH>/<ANONYMIZED_FILE>.py", line 42, in authenticate
    self.perform_authentication(username, password, extra)
  File "<ANONYMIZED_PATH>/<ANONYMIZED_FILE>.py", line 63, in perform_authentication
    raise auth_error
  File "<ANONYMIZED_PATH>/<ANONYMIZED_FILE>.py", line 55, in perform_authentication
    self.twitter_app.start(username, password, extra=extra)
  File "<ANONYMIZED_PATH>/site-packages/tweety/__init__.py", line 21, in wrapper
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/auth.py", line 56, in start
    return await self.sign_in(username, password, extra=_extra)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ANONYMIZED_PATH>/site-packages/tweety/auth.py", line 89, in sign_in
    self.request.set_cookies("", False)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Request' object has no attribute 'set_cookies'

**Comment by alarno** [comment] 2024-11-23 00:05
now, another error appears: Error signing in as xxxxx: 'NoneType' object has no attribute 'ct0' when using:         

app = Twitter("session")
 app.start(username, password)
