### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by harshithagolla** [mahrtayyab/tweety#69] opened 2023-08-16 08:10 UTC
from tweety import Twitter

app = Twitter("session")
app.sign_in(username, password)
target_username = "elonmusk"

user = app.get_user_info(target_username)
all_tweets = app.get_tweets(user)

for tweet in all_tweets:
    print(tweet)

TypeError: unsupported operand type(s) for |: '_SpecialForm' and 'NoneType'

this is the exact error that i am facing with the above code
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from tweety import Twitter
      3 app = Twitter("session")
      4 app.sign_in(username, password)

File ~\anaconda3\lib\site-packages\tweety\__init__.py:4, in <module>
      1 __version__ = "0.9.5"
      2 __author__ = "mahrtayyab"
----> 4 from .bot import BotMethods
      5 from .updates import UpdateMethods
      6 from .auth import AuthMethods

File ~\anaconda3\lib\site-packages\tweety\bot.py:5, in <module>
      2 import re
      3 from typing import Union, Generator
----> 5 from .types import Proxy, UserTweets, Search, User, Tweet, Trends
      6 from .exceptions_ import *
      7 from .session import Session

File ~\anaconda3\lib\site-packages\tweety\types\__init__.py:2, in <module>
----> 2 from .twDataTypes import (
      3     User, Excel, Tweet, Media, Stream, TweetThread, deprecated, Trends
      4 )
      5 from .n_types import UploadedMedia, Proxy
      6 from .search import Search

File ~\anaconda3\lib\site-packages\tweety\types\twDataTypes.py:10, in <module>
      8 import openpyxl
      9 import dateutil
---> 10 from ..utils import *
     13 def deprecated(func):
     14     """
     15 
     16     This is a decorator which can be used to mark functions
   (...)
     19 
     20     """

File ~\anaconda3\lib\site-packages\tweety\utils.py:106, in <module>
    102 def check_sensitive_media_tags(tags):
    103     return [tag for tag in tags if tag in SENSITIVE_MEDIA_TAGS]
--> 106 def find_object(obj: dict, fn: Callable[[dict], bool]) -> Any | None:
    107     if not isinstance(obj, dict):
    108         return None

TypeError: unsupported operand type(s) for |: '_SpecialForm' and 'NoneType'

**Comment by dgw** [comment] 2023-08-16 09:46
Duplicate of #63.

This should be fixed in PyPI version 0.9.6+. https://github.com/mahrtayyab/tweety/commit/e77ef501245890e885c18ddb9c1299c2c77b7b31#diff-1cf24fc2a4a98a93b7312bfedd6ee5d081fac6b988470aad8c41e8f145034037L106-R106

**Comment by harshithagolla** [comment] 2023-08-16 10:12
Got it. Thanks!

**Closed** 2023-08-16 11:29 UTC
