### ISSUE TITLE
UnknownError: [357] Either flow_name or flow_token need to be defined

### ISSUE THREAD

**Issue by JavierS1997** [mahrtayyab/tweety#57] opened 2023-07-23 09:29 UTC
Hi there,

First thank you for all the work put in. This is probably a stupid question, but what might be causing this issue? 
I've created a Twitter dev account, with a project and app.

Thanks

**Comment by mahrtayyab** [comment] 2023-07-23 09:33
Can you please send the traceback.

**Comment by JavierS1997** [comment] 2023-07-23 09:44
```
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-13-8ad29d4d9edf> in <cell line: 4>()
      2 
      3 app = Twitter("session")
----> 4 app.sign_in(username, password)

5 frames
/usr/local/lib/python3.10/dist-packages/tweety/types/n_types.py in _raise_exception(self)
     61             )
     62 
---> 63         raise UnknownError(
     64             error_code=self.error_code,
     65             error_name=TWITTER_ERRORS[self.error_code],

UnknownError: [357] Either flow_name or flow_token need to be defined
```

Thanks for the quick reply!

**Comment by mahrtayyab** [comment] 2023-07-23 17:56
Issue is begin caused by any additional  subtask added to Twitter Login Flow , will be fixed in next release

**Comment by mahrtayyab** [comment] 2023-07-29 16:12
Fixed in latest release , do consider upgrading

**Closed by mahrtayyab** 2023-07-29 16:12 UTC
