### ISSUE TITLE
This statement reports an error in the Linux py 3.7 environment

### ISSUE THREAD

**Issue by Madlife1** [mahrtayyab/tweety#100] opened 2023-09-23 07:19 UTC
"from tweety import Twitter"
This statement reports an error in the Linux py 3.7 environment. I don’t know why. The Windows environment works normally, but the web server gunicorn fails to start.

if __name__ == '__main__':
    from gevent import monkey

    monkey.patch_all(ssl=False)
    app.run(host="0.0.0.0",port=7000)

File "/usr/local/lib/python3.7/dist-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/ggevent.py", line 147, in init_process
    super().init_process()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/dist-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/python/coinbaseAutobuy6000/CoinInfoCenter/app.py", line 9, in <module>
    from service.spider.mainSpider import testmain, testAutoInfoBuy, testCoinbaseAutoInfoBuy
  File "/home/python/coinbaseAutobuy6000/CoinInfoCenter/service/spider/mainSpider.py", line 6, in <module>
    from service.spider.coinbaseSpider import coinbaseWithBuyMethod
  File "/home/python/coinbaseAutobuy6000/CoinInfoCenter/service/spider/coinbaseSpider.py", line 6, in <module>
    from tweety import Twitter
  File "/usr/local/lib/python3.7/dist-packages/tweety/__init__.py", line 4, in <module>
    from .bot import BotMethods
  File "/usr/local/lib/python3.7/dist-packages/tweety/bot.py", line 4, in <module>
    from .types import Proxy, UserTweets, Search, User, Tweet, Trends, Community, CommunityTweets, CommunityMembers
  File "/usr/local/lib/python3.7/dist-packages/tweety/types/__init__.py", line 5, in <module>
    from .n_types import UploadedMedia, Proxy
  File "/usr/local/lib/python3.7/dist-packages/tweety/types/n_types.py", line 5, in <module>
    from httpx._content import encode_multipart_data
  File "/usr/local/lib/python3.7/dist-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/usr/local/lib/python3.7/dist-packages/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/usr/local/lib/python3.7/dist-packages/httpx/_client.py", line 30, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/usr/local/lib/python3.7/dist-packages/httpx/_transports/default.py", line 30, in <module>
    import httpcore
  File "/usr/local/lib/python3.7/dist-packages/httpcore/__init__.py", line 1, in <module>
    from ._api import request, stream
  File "/usr/local/lib/python3.7/dist-packages/httpcore/_api.py", line 5, in <module>
    from ._sync.connection_pool import ConnectionPool
  File "/usr/local/lib/python3.7/dist-packages/httpcore/_sync/__init__.py", line 1, in <module>
    from .connection import HTTPConnection
  File "/usr/local/lib/python3.7/dist-packages/httpcore/_sync/connection.py", line 12, in <module>
    from .._synchronization import Lock
  File "/usr/local/lib/python3.7/dist-packages/httpcore/_synchronization.py", line 13, in <module>
    import trio
  File "/usr/local/lib/python3.7/dist-packages/trio/__init__.py", line 19, in <module>
    from ._core import TASK_STATUS_IGNORED as TASK_STATUS_IGNORED  # isort: skip
  File "/usr/local/lib/python3.7/dist-packages/trio/_core/__init__.py", line 21, in <module>
    from ._local import RunVar
  File "/usr/local/lib/python3.7/dist-packages/trio/_core/_local.py", line 5, in <module>
    from . import _run
  File "/usr/local/lib/python3.7/dist-packages/trio/_core/_run.py", line 2543, in <module>
    from ._io_epoll import EpollIOManager as TheIOManager
  File "/usr/local/lib/python3.7/dist-packages/trio/_core/_io_epoll.py", line 188, in <module>
    @attr.s(slots=True, eq=False, hash=False)
  File "/usr/local/lib/python3.7/dist-packages/trio/_core/_io_epoll.py", line 190, in EpollIOManager
    _epoll = attr.ib(factory=select.epoll)
AttributeError: module 'select' has no attribute 'epoll'

**Comment by Madlife1** [comment] 2023-09-23 07:20
"from tweety import Twitter "   just because this,  i test

**Comment by mahrtayyab** [comment] 2023-10-03 12:21
I am unable to reproduce the error , what is your use case

**Comment by dgw** [comment] 2024-11-24 01:20
Python 3.7 has been EOL for about 17 months. Between that and OP not responding, you can probably close this and move on. It isn't worth trying to fix stuff on such an old Python release IMO 😸

**Closed** 2024-11-24 04:30 UTC
