### ISSUE TITLE
same error

### ISSUE THREAD

**Issue by appnativeitalia** [mahrtayyab/tweety#31] opened 2023-05-19 11:19 UTC
Same error. Not work

```
  File "/usr/local/lib/python3.9/site-packages/tweety/bot.py", line 34, in __ini                                t__
    self.request = Request(max_retries=max_retires, proxy=proxy, cookies=cookies                                )
  File "/usr/local/lib/python3.9/site-packages/tweety/http.py", line 19, in __in                                it__
    self.__guest_token = self._get_guest_token(max_retries)
  File "/usr/local/lib/python3.9/site-packages/tweety/http.py", line 72, in _get                                _guest_token
    for retry in range(max_retries):
```

**Comment by dgw** [comment] 2023-05-19 11:21
Isn't this just a duplicate of #30?

**Comment by mahrtayyab** [comment] 2023-05-19 11:24
Closing for begin duplicate #30

**Closed by mahrtayyab** 2023-05-19 11:24 UTC
